apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myargoapp
  namespace: argocd 
spec:
  project: default
  source:
    repoURL: https://github.com/ashishreddyaleti/ArgoManifest.git
    targetRevision: HEAD
    path: Appdev
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  synPolicy:
    syncOptions: 
    - createNameSpace=true
    automated:
      selfHeal: true
      prune: true